name: integration-tests

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: arnested/go-version-action@v1
      id: go-version
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.go-version.outputs.minimal }}
    - name: Run integration tests
      run: make test-integration
