definitions:
  entities.User:
    properties:
      _id:
        type: string
      email:
        type: string
      name:
        type: string
      passwordHash:
        type: string
      surnames:
        type: string
    type: object
  requests.Login:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  responses.Creation:
    properties:
      insertedId:
        type: string
    type: object
  responses.Login:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/entities.User'
        type: object
    type: object
info:
  contact: {}
  description: Powered by scv-go-framework - https://github.com/scanet9/scv-go-framework
  license: {}
  title: Go Mongo RestAPI
  version: "1.0"
paths:
  /api/users:
    get:
      description: Gets all the users
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.User'
            type: array
      security:
      - Bearer: []
      summary: Get all users
      tags:
      - Users
    post:
      description: Creates a new user
      parameters:
      - description: New user to be created
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Creation'
      summary: Create user
      tags:
      - Users
  /api/users/{id}:
    delete:
      description: Delete a user
      parameters:
      - description: ID
        in: path
        name: ID
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: Delete user
      tags:
      - Users
    get:
      description: Get a user by ID
      parameters:
      - description: ID
        in: path
        name: ID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
      security:
      - Bearer: []
      summary: Get user by ID
      tags:
      - Users
    put:
      description: Update a user
      parameters:
      - description: ID
        in: path
        name: ID
        required: true
        type: string
      - description: User
        in: body
        name: User
        required: true
        schema:
          $ref: '#/definitions/entities.User'
      responses:
        "200":
          description: OK
      security:
      - Bearer: []
      summary: Update user
      tags:
      - Users
  /api/users/email/{email}:
    get:
      description: Get a user by email
      parameters:
      - description: Email
        in: path
        name: email
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entities.User'
      security:
      - Bearer: []
      summary: Get user by email
      tags:
      - Users
  /api/users/login:
    post:
      description: Logs in an user
      parameters:
      - description: Login request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/requests.Login'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Login'
      summary: Login user
      tags:
      - Users
securityDefinitions:
  Bearer:
    in: header
    name: 'Authorization (Format: Bearer {yourToken})'
    type: apiKey
swagger: "2.0"
