name: CD

on:
  push:
    tags:
       - '*'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-mongo-dev:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
    - id: vars
      run: echo ::set-output name=tag::$(echo ${{ github.ref_name }} | xargs basename)
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: scvregistry.azurecr.io
        username: ${{ secrets.AzureContainerRegistry_Username }}
        password: ${{ secrets.AzureContainerRegistry_Password }}
    - name: Build mongo dev
      run: |
        export VERSION=${{ steps.vars.outputs.tag }} && export ENV=dev && export PORT=443 && export DB=mongo && docker-compose build --no-cache
        docker tag go-hexagonal-api-mongo.dev:${{ steps.vars.outputs.tag }} scvregistry.azurecr.io/go-hexagonal-api-mongo.dev:${{ steps.vars.outputs.tag }}
        docker push scvregistry.azurecr.io/go-hexagonal-api-mongo.dev:${{ steps.vars.outputs.tag }}
  
  build-postgres-dev:
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
    - id: vars
      run: echo ::set-output name=tag::$(echo ${{ github.ref_name }} | xargs basename)
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: scvregistry.azurecr.io
        username: ${{ secrets.AzureContainerRegistry_Username }}
        password: ${{ secrets.AzureContainerRegistry_Password }}
    - name: Build postgres dev
      run: |
        export VERSION=${{ steps.vars.outputs.tag }} && export ENV=dev && export PORT=443 && export DB=postgres && docker-compose build --no-cache
        docker tag go-hexagonal-api-postgres.dev:${{ steps.vars.outputs.tag }} scvregistry.azurecr.io/go-hexagonal-api-postgres.dev:${{ steps.vars.outputs.tag }}
        docker push scvregistry.azurecr.io/go-hexagonal-api-postgres.dev:${{ steps.vars.outputs.tag }}

  deploy-mongo-dev:
    runs-on: ubuntu-latest
    needs: build-mongo-dev
    environment: mongo-dev
    steps:
    - id: vars
      run: echo ::set-output name=tag::$(echo ${{ github.ref_name }} | xargs basename)
    - name: Deploy mongo dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'go-hexagonal-api-mongo-dev'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Mongo_Dev }}
        images: 'scvregistry.azurecr.io/go-hexagonal-api-mongo.dev:${{ steps.vars.outputs.tag }}'

  deploy-postgres-dev:
    runs-on: ubuntu-latest
    needs: build-postgres-dev
    environment: postgres-dev
    steps:
    - id: vars
      run: echo ::set-output name=tag::$(echo ${{ github.ref_name }} | xargs basename)
    - name: Deploy postgres dev
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'go-hexagonal-api-postgres-dev'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_Postgres_Dev }}
        images: 'scvregistry.azurecr.io/go-hexagonal-api-postgres.dev:${{ steps.vars.outputs.tag }}'
