name: CI

on:
  push:
    branches:
      - main

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/actions/unit-tests.yml
    
  run-integration-tests:
      runs-on: ubuntu-latest
      needs: integration-tests
      steps:
      - uses: ./.github/actions/integration-tests.yml
